### ISSUE TITLE
File does not conform during VRecord Policy Check for FFV1

### ISSUE THREAD

**Issue by SophiaFrancis1** [amiaopensource/vrecord#838]
Hi, 

We are just starting to capture in FFV1 -- previously we were capturing in Uncompressed Quicktime. I keep getting this warning off and on. I'm not sure what to think of it and it seems to just pop up randomly. Sometimes it is fine an other times it is not. If someone might be able to shed some light on this, that would be very helpful. Unfortunately, it seems I cannot give this in the original format as GitHub doesn't allow file up loads through their Issue reporter that are XML -- so I have had to convert it to TXT.
[p0479_gree_99-2144743420-2441_v01_mediaconchreport copy.txt](https://github.com/user-attachments/files/17261321/p0479_gree_99-2144743420-2441_v01_mediaconchreport.copy.txt)

Thank you so much, 
Sophia

**Comment by privatezero** [comment]
Hi @SophiaFrancis1 - which version of vrecord are you on? This sounds similar to some issues another user was having that seem to have been resolved with the most recent release, so that might be something to try out if you are a couple versions behind.

**Comment by bturkus** [comment]
We're having the same issue on one computer; I can share details and a sample file tomorrow, but updating/upgrading did not solve the problem, nor did "vrecord -x"

I've started to suspect that the problem may lie in part with MediaConch, but I'm getting such inconsistent results it's hard to even report an issue.

**Comment by SophiaFrancis1** [comment]
Hi,

We are running the most recent version. I read the prior reports and also had some additional issues (now resolved) so we updated to the latest, the one from August I believe (I'm not at work so I cannot check).

Yes, exactly it is only occassionally failing. Not all the time. It is really strange. Glad we're not the only ones. I just worry the file is not truly compliant or if it's just a fluke.

**Comment by privatezero** [comment]
Thanks both of you for the follow-up! If it is intermittent that certainly complicates things (and eliminates the possibility of a mediaconch parsing problem like some of the other recent issues). I'll see if I can reproduce anything on my end.

**Comment by bturkus** [comment]
Hi @privatezero,

Just to add recent observations to the thread: We've been experiencing this issue with intermittent failures during MediaConch policy checks on a few different computers. We are running macOS 14.7 with Blackmagic Desktop Video 14.2.1 and vrecord version 2024-08-28. We've tried various troubleshooting steps, such as updating Xcode and command line tools, reinstalling FFmpegDecklink and vrecord, and testing different ways of stopping the capture (red button, escape key, and q key).

Interestingly, we’ve noticed that shorter captures (under a few minutes) tend to pass the policy check, while longer captures fail. The failures are consistently related to MKV finalization, specifically missing SeekHead and Cues elements in the Matroska file.

It seems like the file is not being finalized properly in some cases, but it's difficult to pinpoint exactly what's causing the issue as the problem appears sporadically.

Looking forward to hearing others' thoughts!

Best,

Ben

**Comment by libbyhopfauf** [comment]
@privatezero I am having the same issue on one of our computers, but it is happening with almost every single capture. I have also tried all of the same troubleshooting steps that @bturkus mentioned, but it's not be resolved. It seems to mainly be an issue with when I manually end the capture by exiting out of the window prior to the recording time that was entered in vrecord -e. 

Here are the specs for the computer I have been running this on:

MacMini M1 chip
Sonoma 14.7
vrecord 2024-08-28

I have uploaded the files for two very short captures. The first one I exited the capture manually by clicking on the "x" of the ffmplay window. The second one I set the recording time for "0.25" and let vrecord end the capture. When I let vrecord end the capture, the file passed. 
[manual ending capture](https://drive.google.com/drive/folders/1yYSoDSAhn40oH2yvTyllALSAJ4czszID?usp=sharing)
[vrecord ended capture](https://drive.google.com/drive/folders/1OGW7SLyYcYcjjkcoP3TpM3YLRKASf-z0?usp=sharing)

**Comment by libbyhopfauf** [comment]
Okay, so that's not entirely true. I just let a video go until vrecord stopped the recording and it did not pass the FFV1 policy. So I'm not sure what the pattern is, but almost every time, captures fail the policy check on this computer.

**Comment by SophiaFrancis1** [comment]
I had a similar thought initially myself. It seemed at first to me that pressing the button in the corner to exit was causing it, but then I realized it was also happening when I was hitting escape (though perhaps less frequently). It seems that, as some have already mentioned, it could be an issue with the cessation of recording as an entirety perhaps?

**Comment by EmCNabs** [comment]
Having the same issues here.

I set a recording time for vrecord to end the capture, then during file checking it comes back with the error 
` 2024-10-16T14:46:18 - File did not pass vrecord policy check for FFV1 video and may not conform to digital preservation standards. Try another file?
 2024-10-16T14:46:18 - See /Users/medialab/Desktop/01_vrecord_Capture/01_In_QC_Processing/2012_79_2_170_1a_PM/2012_79_2_170_1a_PM_mediaconchreport.xml for a full MediaConch policy report.`

As @libbyhopfauf mentioned, vrecord then creates .scc and eia608data.txt files for the captures that fail the FFV1 policy.

Computer Specs:
MacMini 6-Core Intel Core i7
Sonoma 14.7
vrecord ver. 2024-08-28

Latest Transfer Side Files
[2012_79_2_170_1a_PM_capture_options.log](https://github.com/user-attachments/files/17414952/2012_79_2_170_1a_PM_capture_options.log)
[2012_79_2_170_1a_PM_mediaconchreport_xml.txt](https://github.com/user-attachments/files/17414988/2012_79_2_170_1a_PM_mediaconchreport_xml.txt)
[2012_79_2_170_1a_PM_scc.txt](https://github.com/user-attachments/files/17415001/2012_79_2_170_1a_PM_scc.txt)
[2012_79_2_170_1a_PM_frame_eia608data.txt](https://github.com/user-attachments/files/17414956/2012_79_2_170_1a_PM_frame_eia608data.txt)

**Comment by privatezero** [comment]
Hi all, We've pushed a new release that might fix this on your ends - try `brew update && brew upgrade vrecord` and let us know if things are working better or not.

**Comment by SophiaFrancis1** [comment]
Just ran the new vrecord and seemed to not have that error with the policy get thrown with the video I just captured, but since it was sporadic, I will keep testing along with others (anyone feel free to jump in) and let you know if it seems to be resolved. Thank you so much!

**Comment by privatezero** [comment]
thanks for testing @SophiaFrancis1! Hopefully all will remain copacetic for you and the other users reporting.

**Comment by EmCNabs** [comment]
> Hi all, We've pushed a new release that might fix this on your ends - try `brew update && brew upgrade vrecord` and let us know if things are working better or not.

Updated & Upgraded! Success!

Captured a video and received no FFV1 policy error messages. It was under 10min though, so will report back if an error pops up again on something longer.

Thank you!

**Comment by libbyhopfauf** [comment]
@privatezero I can also confirm that after updating that I was able to capture multiple tapes of varying lengths (between 15 minutes to 2 hours) yesterday and they all passed the policy check. Yay!!

**Comment by privatezero** [comment]
Great! Thanks you all - I'll close this as hopefully resolved. If this becomes a problem again, definitely re-open or make another issue!

**Comment by privatezero** [comment]
resolved in https://github.com/amiaopensource/vrecord/pull/842
